name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚨 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'ci'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'dependencies'
      - 'documentation'
  default: patch

template: |
  ## What's Changed
  $CHANGES