name: 'Project "Piper"'
description: 'CI/CD tooling for the SAP Ecosystem'
inputs:
  command:
    description: 'command to run'
    required: true
    default: 'help'
  flags:
    description: 'flags/arguments for command'
    required: false
    default: ''
  piper-version:
    description: 'specify a version of the piper binary to use, may be "master", "latest" or a released tag'
    required: false
    default: 'latest'
outputs:
  binary:
    description: Path to installed piper binary
runs:
  using: 'node12'
  main: 'dist/index.js'
