name: 'Project "Piper" Action'
description: 'CI/CD tooling for the SAP Ecosystem'
inputs:
  step-name:
    description: 'Name of Piper step to execute'
    required: false
  command:
    description: 'Name of Piper step to execute'
    deprecationMessage: 'Deprecated, use step-name'
    required: false
  flags:
    description: 'Flags/arguments for step'
    required: false
  piper-version:
    description: 'Specify Piper binary to use, may be "master", "latest" or a released tag'
    required: false
  piper-owner:
    description: 'Owner of the repository from where to load the Piper binary'
    required: false
  piper-repository:
    description: 'Repository from where to load the Piper binary'
    required: false
  sap-piper-version:
    description: 'Specify SAP Piper binary to use, may be "master", "latest" or a released tag'
    required: false
  sap-piper-owner:
    description: 'Owner of the repository from where to load the SAP-internal Piper binary'
    required: false
  sap-piper-repository:
    description: 'Repository from where to load the SAP-internal Piper binary'
    required: false
  github-token:
    description: 'Token to access GitHub API'
    required: false
  github-enterprise-token:
    description: 'Token to access GitHub Enterprise API'
    required: false
  docker-image:
    description: 'Docker image to run Piper in'
    required: false
  docker-options:
    description: 'Docker options to start the container with'
    required: false
  docker-env-vars:
    description: 'The environment variables to pass to the docker container, as JSON string (e.g. {"testKey": "testValue"})'
    required: false
  sidecar-image:
    description: 'Docker image to run as a sidecar next to the main container'
    required: false
  sidecar-options:
    description: 'Docker options to start the sidecar container with'
    required: false
  sidecar-env-vars:
    description: 'The environment variables to pass to the sidecar container'
    required: false
  custom-defaults-paths:
    description: 'Specify comma-separated custom defaults paths'
    required: false
  custom-stage-conditions-path:
    description: 'Specify custom stage conditions YAML file paths. It can be path in filesystem, GitHub raw content URL or GitHub release asset url'
    required: false
  export-pipeline-environment:
    description: 'Exports pipeline environment to share between jobs as variable with the name "pipelineEnv"'
    required: false
  create-check-if-step-active-maps:
    description: 'Creates maps with active stages and steps using checkIfStepActive and outputs them at `.pipeline/stage_out.json` and `.pipeline/step_out.json`'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'play'
  color: 'green'
