name: Dependency Check

on: [push, pull_request]

jobs:
  check-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check for unused dependencies
        run: npx depcheck --ignores="@types/*,eslint*,babel*,jest*" --skip-missing true
