name: Trigger Mirror

on:
  delete:
  push:
    branches-ignore:
      - 'renovate/**'
  workflow_dispatch:
  release:
    types: [released]

# For dynamic naming of the workflow runs
run-name: >-
  Trigger ${{ github.event_name }}:
  ${{
    github.event_name == 'push' && github.ref_name ||
    github.event_name == 'release' && github.event.release.tag_name ||
    github.event_name == 'delete' && github.event.ref ||
    ''
  }}

# This will ensure that only one workflow is active for each event (and it's ref) by canceling previously triggered active workflow runs.
# For example, if there are multiple pushes to a branch in a short time frame, only the last one will be processed, the rest will be canceled.\
# See docs: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event_name }}-${{
      github.event_name == 'push' && github.ref_name ||
      github.event_name == 'release' && github.event.release.tag_name ||
      github.event_name == 'delete' && github.event.ref ||
      ''
    }}
  cancel-in-progress: true

jobs:
  trigger_mirror:
    name: Trigger Mirror Workflow
    runs-on: ubuntu-latest
    env:
      EVENT_TYPE: >-
        ${{
          github.event_name == 'workflow_dispatch' && 'mirror-push' ||
          github.event_name == 'push' && 'mirror-push' ||
          github.event_name == 'release' && 'mirror-tag' ||
          github.event_name == 'delete' && 'mirror-delete-ref' || ''
        }}
      PAYLOAD_KEY: >-
        ${{
          github.event_name == 'workflow_dispatch' && 'source_branch' ||
          github.event_name == 'push' && 'source_branch' ||
          github.event_name == 'release' && 'tag_name' ||
          github.event_name == 'delete' && 'delete_ref' || ''
        }}
      PAYLOAD_VALUE: >-
        ${{
          github.event_name == 'workflow_dispatch' && github.ref_name ||
          github.event_name == 'push' && github.ref_name ||
          github.event_name == 'release' && github.event.release.tag_name ||
          github.event_name == 'delete' && github.event.ref || ''
        }}
    steps:
      - name: Trigger ${{ env.EVENT_TYPE}} with payload ${{ env.PAYLOAD_KEY}}=${{ env.PAYLOAD_VALUE}}
        if: github.event_name == 'push'
        run: |
          echo "Triggering mirror workflow for branch: $BRANCH_NAME"

          response=$(curl -s -w "%{http_code}" -o mirror_response.txt \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.MIRROR_WORKFLOW_TOKEN }}" \
            --max-time 30 \
            "${{ secrets.MIRROR_API_URL }}/dispatches" \
            -d '{
                  "event_type": "${{ env.EVENT_TYPE}}",
                  "client_payload": {
                    "source_repo": "${{ github.repository }}",
                    "${{ env.PAYLOAD_KEY}}": "${{ env.PAYLOAD_VALUE }}"
                  }
                }'
          )

          status_code="${response: -3}"

          if [ "$status_code" -eq 204 ]; then
            echo "Mirror workflow triggered successfully."
          else
            echo "Failed to trigger mirror workflow. Status code: $status_code"
            echo "Response body:"
            cat mirror_response.txt
            exit 1
          fi
