name: Trigger Mirror

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  trigger_mirror:
    name: Trigger Mirror Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger mirror workflow
        run: |
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.MIRROR_WORKFLOW_TOKEN }}" \
            -w "%{http_code}" \
            --max-time 30 \
            "${{ secrets.MIRROR_API_URL }}/dispatches" \
            -d '{"event_type":"mirror_trigger","client_payload":{"source_repo":"https://github.com/${{ github.repository }}"}}')

          status_code=${response: -3}
          if [ "$status_code" -ne 204 ]; then
            echo "Failed to trigger mirror workflow. Status code: $status_code"
            exit 1
